#
# $ docker build -f Dockerfile -t ginger .
#
# @maintainer <farwish@foxmail.com>
#

FROM golang:1.14.2

# We need to set proxy on our server!
RUN go env -w GO111MODULE=on
RUN go env -w GOPROXY=https://goproxy.io,direct

WORKDIR /go/src/app

COPY . .

# Build binary by ourselves, So we not depend on other workflow
RUN go get -d -v ./...
RUN go install -v ./...
RUN go build -o dist/ginger -v .

EXPOSE 8090

# Important to load right config
ENV GIN_MODE="release"
RUN echo $GIN_MODE

ENTRYPOINT ["./dist/ginger"]


